stockScreener/dataHandler/urls.py
from django.urls import path
from .views import dataToHtml, captureJson

urlpatterns = [
    
    path('loadedData/', dataToHtml, name='ReturnedData'),
    path('captureData/', captureJson, name= 'captureJson'),

    
]

stockScreener/home/urls.py
from django.urls import path
from .views import landPage

urlpatterns = [
    
    path('', landPage, name='home'),
    
]

stockScreener/stockScreener/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('home.urls', 'home'), namespace= 'home')),
    path('dataWork/', include(('dataHandler.urls', 'dataHandler'), namespace= 'dataHandler')),
]

stockScreener/dataHandler/models.py
from django.db import models

# Create your models here.

stockScreener/dataHandler/views.py
from django.shortcuts import render, HttpResponse
from .UserDataFrame import DataContext
from django.views.decorators.csrf import csrf_exempt
import json as js
from main import writeJson



@csrf_exempt
def captureJson(request):
    
    json = request.POST.get('data')
    setData = js.loads(json)
    
    writeJson(setData)
    
    return HttpResponse("Success")
    
    

@csrf_exempt
def dataToHtml(request):
    
    row = DataContext(request)
    row  = row.populateDataContext()
    
    try:

        tickers = row['Ticker'].values()
        companies = row['Company Name'].values()
        sectors = row['Sector'].values()
        industry = row['Industry'].values()
        mCap = row['Market Cap'].values()
        price = row['Price'].values()
        pE = row['P/E'].values()
        dYield = row['Dividend Yield'].values()
        aRec = row['Analyst Recommendation'].values()
        
        return render(request, 'dataPage/dataView.html',         
            {
                'Tickers': tickers, 
                'companyName': companies,
                'Sectors': sectors,
                'Industry': industry,
                'marketCap': mCap,
                'Price': price,
                'PE': pE,
                'Dividend': dYield,
                'recommend':aRec 
            })
        
    except KeyError:
        
        return render(request, 'dataPage/noStocks.html')
        
    
    
    
    
    

stockScreener/home/views.py
from django.shortcuts import render, redirect
from dataHandler.views import dataToHtml
from django.views.decorators.csrf import csrf_exempt


@csrf_exempt
def landPage(request):
    
    context = {}
    
    return render(request, 'home/index.html', context)





    
    

    

stockScreener/templates/dataPage/dataView.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<meta charset="UTF-8">

<head>
    <title>Fundamental Stock Screener</title>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" type="text/css" href="/static/css/styles.css">
    <link rel="icon" type="image/x-icon" href="/static/css/favicon.png">
</head>

    <body>

        <!-- Top Section -->
        <div class="header">
            <h1>FUNDAMENTAL STOCK SCREENER</h1>
        </div>

        <div class="goHome">
            <button type="button" id="homeButton">Go Back to Preferences</button>
        </div>
        <br>
        <br>

        <!-- Valid Stocks Table -->
        <table id="thetable" style="width:100%">
            <thead>
                <tr>
                <th>Ticker</th>
                <th>Company</th>
                <th>Sector</th>
                <th>Industry</th>
                <th>Market Cap</th>
                <th>Price</th>
                <th>P/E (TTM)</th>
                <th>Dividend Yield</th>
                <th>Analyst Recommendation</th>
                </tr>
            </thead>
            <tbody>
            <tr>
                {% for tick in Tickers %}
        
                <td> {{ tick }} </td>

                {% endfor %}
            </tr>
            
            <tr>
                {% for c in companyName %}
        
                <td>  {{ c }} </td>

                {% endfor %}
            </tr>

            <tr>
                {% for s in Sectors %}
        
                <td>  {{ s }} </td>

                {% endfor %}
            </tr>

            <tr>
                {% for I in Industry %}
        
                <td>  {{ I }} </td>

                {% endfor %}
            </tr>
            <tr>
                {% for m in marketCap %}
        
                <td style="text-align: center;">  {{ m }} </td>

                {% endfor %}
            </tr>
            <tr>
                {% for p in Price %}
        
                    <td style="text-align: center;">  ${{ p }} </td>

                {% endfor %}
            </tr>
            <tr>
                {% for e in PE %}

                    <td style="text-align: center;">  {{ e }} </td>

                {% endfor %}
            </tr>
            <tr>
                {% for b in Dividend %}

                {% if b == "-"%}

                    <td style="text-align: center;">  {{ b }} </td>

                {% else %}

                    <td style="text-align: center;">  {{ b }}% </td>

                {% endif %}

                {% endfor %}
            </tr>
            <tr>
                {% for r in recommend %}
        
                    {% if r == "strong_buy" %}

                        <td style="background-color: #018f87; text-align: center;">  Strong Buy </td>

                    {% endif %}

                    {% if r == "buy" %}

                        <td style="background-color: #01bf73; text-align: center;">  Buy </td>

                    {% endif %}

                    {% if r == "hold" %}

                        <td style=" background-color: #ffdc48; text-align: center;">  Hold </td>

                    {% endif %} 

                    {% if r == "underperform" %}

                        <td style="background-color: #fea23d; text-align: center;">  Underperform </td>

                    {% endif %} 

                    {% if r == "sell" %}

                        <td style="background-color: #ff333a; text-align: center;">  Sell </td>
                        

                    {% endif %}

                {% endfor %}
            </tr>
            </tbody> 
        </table>
        
        <br>
        <br>
        <div class="goHome">
            <button type="button" id="homeButton">Go Back to Preferences</button>
        </div>

        <!-- Footer -->
        <br>
        <div class="footer">
            <p>* Disclaimer: This is just a resource and should not be used as investment advice.
                The creators, hosts, and anyone else related to this site are not liable for any
                losses that may incur.
            </p>
        </div>

    </body>

    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
    <script src="scripts/jquery.table.transpose.min.js"></script>
    <script type="text/javascript">
    
        $(document).ready(function () {
    
            var t = $('#thetable tbody').eq(0);
            var r = t.find('tr');
            var cols= r.length;
            var rows= r.eq(0).find('td').length;
            var cell, next, tem, i = 0;
            var tb= $('<tbody></tbody>');
        
            while(i<rows){
                cell= 0;
                tem= $('<tr></tr>');
                while(cell<cols){
                    next= r.eq(cell++).find('td').eq(0);
                    tem.append(next);
                }
                tb.append(tem);
                ++i;
            }
            $('#thetable').append(tb);
            $('#thetable').show();

            $(".goHome").click(function (e) {
                window.location.href = '{% url "home:home"  %}';
            });
    
        });
    
</script>


</html>

stockScreener/templates/dataPage/noStocks.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<meta charset="UTF-8">

<head>
    <title>Fundamental Stock Screener</title>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" type="text/css" href="/static/css/styles.css">
    <link rel="icon" type="image/x-icon" href="/static/css/favicon.png">
</head>

    <body>

        <!-- Top Section -->
        <div class="header">
            <h1>FUNDAMENTAL STOCK SCREENER</h1>
        </div>
        <!-- -->
        
        <div class="goHome">
            <button type="button" id="homeButton">Go Back to Preferences</button>
        </div>  
        <br>
        <br>

        <h1 style="text-align: center">The preferences you entered either returned no matching stocks or were invalid.</h1>

        <!-- Footer -->
        <br>
        <div class="footer">
            <p>* Disclaimer: This is just a resource and should not be used as investment advice.
                The creators, hosts, and anyone else related to this site are not liable for any
                losses that may incur.
            </p>
        </div>


    </body>

    <script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
    <script type="text/javascript">
    $(document).ready(function () {

        $(".goHome").click(function (e) {
                window.location.href = '{% url "home:home"  %}';
            });

    });
    </script>

</html>

stockScreener/templates/home/dataView.html
<!DOCTYPE html>

<html lang="en">


    <body>
        {% for ticker in Tickers %}
        
            <p>  {{ ticker }} </p>
    
        {% endfor %}
    </body>

</html>